### ISSUE TITLE
Uwagi wstępne

### ISSUE THREAD

**Issue by flaminka** [flaminka/CreditCardFraud#1]
Moje luźne uwagi na początek:

1. podstawowy plik notebookowy w pythonie stworzony, można go oglądać wprost
z githuba: https://github.com/flaminka/CreditCardFraud
2. dodam Was jako kolaboratorow do githuba ale musicie mi podac nazwy swoich użytkowników na githubie, wtedy będziecie mogły wrzucać bez problemu tam pliki, bez mojego zatwierdzania tego
3. dane można ściągnąć z kaggle'a
4. trzeba by poczytać/przejrzeć ten artykuł (w załączeniu) oraz inne na temat tak niezbalansowanych danych (albo konkretniej oszustw w kartach kredytowych); słowa kluczowe do szukania w necie w stylu "dependent COST-SENSITIVE learning" 
5. po co ten czas (zmienna TIME) może się przydać? pytanie otwarte przemyśleć
6. ogarnąć tą miarę AUPRC (wzór konkretnie, tak by to byla juz tylko kwestia
implementacji)
7. obczaić dyskusje i kernele na kagglu w poszukiwaniu inspiracji
tam jest to często robione w pythonie i często linkowane sa artykuly pomocne, więc warto
8. czy macie możliwość tworzenia czegoś w pythonie? tj. możecie zainstalować go u siebie tak by coś robić w nim?
9. zaczęłabym od zbudowania drzewka lub regresji logistycznej i pobawienia sie z parametrami, ew. sa jakies przepróbkowania/niedopróbkowania (powtarzamy obserwacje z klasą 1)
10. trzeba zadbac o dobra jakosc zbioru testowego, bo nikt nam nie będzie sprawdzał tego na zbiorze testowym
11. wizualizacja tego jakoś

**Comment by malinowskam** [comment]
Ad8 Tak mam pythona na kompie ;)
